<?php

namespace AppBundle\Repository;

/**
 * StadionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StadionRepository extends \Doctrine\ORM\EntityRepository
{
}
