# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
services:
    app.api_user_provider:
        class: AppBundle\Entity\UserProvider
    api_provider:
        class: AppBundle\Service\ApiService
        arguments: ['%api_location%']